-- 2025-2026 Blockbuster Seed Data for buffyisawesomeMDB
-- Categories: in-theaters, coming-soon, streaming-soon, major-blockbuster, for-you

-- 🍿 In Theaters Now
INSERT INTO movies (title, type, year, duration, age_rating, star_rating, vote_count, poster_url, backdrop_url, trailer_url, genres, language, category, weekend_gross, total_gross, description) VALUES
('The Batman – Part II', 'Movie', 2026, '2h 45m', 'PG-13', 8.4, '124K', 'https://picsum.photos/seed/batman2/300/450', 'https://picsum.photos/seed/batman2-bg/1200/600', 'https://www.youtube.com/embed/dQw4w9WgXcQ', ARRAY['Action', 'Crime', 'Drama'], 'English', 'in-theaters', '$185M', '$185M', 'Robert Pattinson returns as the Dark Knight in Matt Reeves'' noir-soaked sequel. Gotham faces a new threat rising from the ashes of the flooded city.'),
('Shrek 5', 'Movie', 2026, '1h 35m', 'PG', 7.8, '89K', 'https://picsum.photos/seed/shrek5/300/450', 'https://picsum.photos/seed/shrek5-bg/1200/600', 'https://www.youtube.com/embed/dQw4w9WgXcQ', ARRAY['Animation', 'Comedy', 'Family'], 'English', 'in-theaters', '$62M', '$680M', 'The ogre is back after 16 years! Shrek and Fiona navigate parenthood while a new fairy tale villain threatens Far Far Away.'),
('Dune: Part Three', 'Movie', 2026, '2h 55m', 'PG-13', 9.1, '210K', 'https://picsum.photos/seed/dune3/300/450', 'https://picsum.photos/seed/dune3-bg/1200/600', 'https://www.youtube.com/embed/dQw4w9WgXcQ', ARRAY['Sci-Fi', 'Adventure', 'Drama'], 'English', 'in-theaters', '$45M', '$890M', 'Denis Villeneuve concludes his Dune trilogy with Paul Atreides facing the consequences of the jihad unleashed in his name.'),
('Avengers: Doomsday', 'Movie', 2026, '2h 38m', 'PG-13', 8.7, '340K', 'https://picsum.photos/seed/doomsday/300/450', 'https://picsum.photos/seed/doomsday-bg/1200/600', 'https://www.youtube.com/embed/dQw4w9WgXcQ', ARRAY['Action', 'Adventure', 'Superhero'], 'English', 'in-theaters', '$112M', '$1.8B', 'Robert Downey Jr. returns as Doctor Doom. The Multiverse Saga reaches its cataclysmic climax in the biggest Marvel event yet.'),
('Deadpool & Wolverine 2', 'Movie', 2026, '2h 10m', 'R', 8.3, '195K', 'https://picsum.photos/seed/deadpool2/300/450', 'https://picsum.photos/seed/deadpool2-bg/1200/600', 'https://www.youtube.com/embed/dQw4w9WgXcQ', ARRAY['Action', 'Comedy', 'Superhero'], 'English', 'in-theaters', '$52M', '$1.2B', 'The Merc with a Mouth and the grumpiest X-Man reunite for another chaotic, fourth-wall-breaking, R-rated adventure through the multiverse.');

-- 🎟️ Coming Soon to Theaters
INSERT INTO movies (title, type, year, duration, age_rating, star_rating, vote_count, poster_url, backdrop_url, trailer_url, genres, language, category, release_date, like_count, love_count, is_coming_soon, description) VALUES
('Spider-Man: Beyond the Spider-Verse', 'Movie', 2026, '2h 20m', 'PG', 9.0, '85K', 'https://picsum.photos/seed/spiderverse3/300/450', 'https://picsum.photos/seed/spiderverse3-bg/1200/600', 'https://www.youtube.com/embed/dQw4w9WgXcQ', ARRAY['Animation', 'Action', 'Adventure'], 'English', 'coming-soon', 'SEP 15', 340, 210, true, 'Miles Morales faces his ultimate challenge as the Spider-Verse trilogy concludes in spectacular, groundbreaking animation.'),
('The Mandalorian & Grogu', 'Movie', 2026, '2h 15m', 'PG-13', 8.5, '62K', 'https://picsum.photos/seed/mando/300/450', 'https://picsum.photos/seed/mando-bg/1200/600', 'https://www.youtube.com/embed/dQw4w9WgXcQ', ARRAY['Sci-Fi', 'Adventure', 'Action'], 'English', 'coming-soon', 'NOV 22', 280, 195, true, 'Din Djarin and Grogu return in their first feature film. A new threat emerges from the Outer Rim that could change the galaxy forever.'),
('Frozen 3', 'Movie', 2026, '1h 50m', 'PG', 7.5, '45K', 'https://picsum.photos/seed/frozen3/300/450', 'https://picsum.photos/seed/frozen3-bg/1200/600', 'https://www.youtube.com/embed/dQw4w9WgXcQ', ARRAY['Animation', 'Musical', 'Family'], 'English', 'coming-soon', 'DEC 20', 190, 140, true, 'Elsa discovers the true origin of her powers in a journey beyond Arendelle that reveals ancient magic and a long-lost kingdom.'),
('Star Wars: New Jedi Order', 'Movie', 2027, '2h 30m', 'PG-13', 8.8, '78K', 'https://picsum.photos/seed/starwars-njo/300/450', 'https://picsum.photos/seed/starwars-njo-bg/1200/600', 'https://www.youtube.com/embed/dQw4w9WgXcQ', ARRAY['Sci-Fi', 'Adventure', 'Action'], 'English', 'coming-soon', 'MAY 22', 420, 310, true, 'Rey rebuilds the Jedi Order 15 years after The Rise of Skywalker. A new darkness stirs in the Unknown Regions.');

-- 📺 Going to Streaming Soon
INSERT INTO movies (title, type, year, duration, age_rating, star_rating, vote_count, poster_url, backdrop_url, trailer_url, genres, language, category, streaming_on, release_date, description) VALUES
('Superman', 'Movie', 2025, '2h 30m', 'PG-13', 8.4, '180K', 'https://picsum.photos/seed/superman25/300/450', 'https://picsum.photos/seed/superman25-bg/1200/600', 'https://www.youtube.com/embed/dQw4w9WgXcQ', ARRAY['Action', 'Adventure', 'Superhero'], 'English', 'streaming-soon', ARRAY['Max'], 'AUG 15', 'James Gunn''s fresh take on the Man of Steel. David Corenswet soars as Clark Kent in a hopeful, heartfelt reboot that reminds us why we need Superman.'),
('Fantastic Four: First Steps', 'Movie', 2025, '2h 5m', 'PG-13', 8.0, '145K', 'https://picsum.photos/seed/fantastic4/300/450', 'https://picsum.photos/seed/fantastic4-bg/1200/600', 'https://www.youtube.com/embed/dQw4w9WgXcQ', ARRAY['Action', 'Adventure', 'Superhero'], 'English', 'streaming-soon', ARRAY['Disney+'], 'AUG 22', 'Marvel''s First Family finally gets the MCU treatment they deserve. Pedro Pascal leads as Reed Richards in a retro-futuristic 1960s adventure.'),
('Jurassic World: Rebirth', 'Movie', 2025, '2h 15m', 'PG-13', 7.6, '132K', 'https://picsum.photos/seed/jurassic-rebirth/300/450', 'https://picsum.photos/seed/jurassic-rebirth-bg/1200/600', 'https://www.youtube.com/embed/dQw4w9WgXcQ', ARRAY['Action', 'Adventure', 'Sci-Fi'], 'English', 'streaming-soon', ARRAY['Peacock'], 'SEP 1', 'Scarlett Johansson leads the dinosaur franchise revival. A daring expedition to a remote island reveals dinosaurs thriving in ways no one imagined.'),
('Mission: Impossible – The Final Reckoning', 'Movie', 2025, '2h 45m', 'PG-13', 8.6, '210K', 'https://picsum.photos/seed/mi-final/300/450', 'https://picsum.photos/seed/mi-final-bg/1200/600', 'https://www.youtube.com/embed/dQw4w9WgXcQ', ARRAY['Action', 'Thriller', 'Adventure'], 'English', 'streaming-soon', ARRAY['Paramount+'], 'SEP 8', 'Tom Cruise''s final mission as Ethan Hunt. The stakes have never been higher as the IMF faces an enemy that knows every move they''ll make.'),
('Wicked: Part Two', 'Movie', 2025, '2h 30m', 'PG', 8.3, '165K', 'https://picsum.photos/seed/wicked2/300/450', 'https://picsum.photos/seed/wicked2-bg/1200/600', 'https://www.youtube.com/embed/dQw4w9WgXcQ', ARRAY['Musical', 'Fantasy', 'Drama'], 'English', 'streaming-soon', ARRAY['Prime Video'], 'SEP 15', 'The billion-dollar musical phenomenon concludes. Elphaba and Glinda''s paths diverge as Oz descends into darkness, leading to the fateful melting we all know.');

-- ⭐ Major Blockbusters
INSERT INTO movies (title, type, year, duration, age_rating, star_rating, vote_count, poster_url, backdrop_url, trailer_url, genres, language, category, total_gross, description) VALUES
('Avatar: Fire and Ash', 'Movie', 2025, '3h 12m', 'PG-13', 8.2, '350K', 'https://picsum.photos/seed/avatar3/300/450', 'https://picsum.photos/seed/avatar3-bg/1200/600', 'https://www.youtube.com/embed/dQw4w9WgXcQ', ARRAY['Sci-Fi', 'Adventure', 'Fantasy'], 'English', 'major-blockbuster', '$2.3B', 'James Cameron''s third Pandora epic introduces the ash people — a volcanic Na''vi clan with a dark connection to human colonization.');

-- 🌸 For You (sci-fi epics, superhero sagas & Nolan vibes)
INSERT INTO movies (title, type, year, duration, age_rating, star_rating, vote_count, poster_url, backdrop_url, trailer_url, genres, language, category, description) VALUES
('Dune: Part Three', 'Movie', 2026, '2h 55m', 'PG-13', 9.1, '210K', 'https://picsum.photos/seed/dune3/300/450', 'https://picsum.photos/seed/dune3-bg/1200/600', 'https://www.youtube.com/embed/dQw4w9WgXcQ', ARRAY['Sci-Fi', 'Adventure', 'Drama'], 'English', 'for-you', 'Villeneuve''s grand finale — sandworms, spice, and destiny collide in the most visually stunning chapter yet.'),

('The Batman – Part II', 'Movie', 2026, '2h 45m', 'PG-13', 8.4, '124K', 'https://picsum.photos/seed/batman2/300/450', 'https://picsum.photos/seed/batman2-bg/1200/600', 'https://www.youtube.com/embed/dQw4w9WgXcQ', ARRAY['Action', 'Crime', 'Drama'], 'English', 'for-you', 'Dark, noir, detective-driven Gotham at its finest. Pattinson deepens the cowl in this relentless sequel.'),

('Superman', 'Movie', 2025, '2h 30m', 'PG-13', 8.4, '180K', 'https://picsum.photos/seed/superman25/300/450', 'https://picsum.photos/seed/superman25-bg/1200/600', 'https://www.youtube.com/embed/dQw4w9WgXcQ', ARRAY['Action', 'Adventure', 'Superhero'], 'English', 'for-you', 'James Gunn''s hopeful, heartfelt reboot — a Superman who believes in the goodness of humanity.'),

('Spider-Man: Beyond the Spider-Verse', 'Movie', 2026, '2h 20m', 'PG', 9.0, '85K', 'https://picsum.photos/seed/spiderverse3/300/450', 'https://picsum.photos/seed/spiderverse3-bg/1200/600', 'https://www.youtube.com/embed/dQw4w9WgXcQ', ARRAY['Animation', 'Action', 'Adventure'], 'English', 'for-you', 'Multiverse animation at its absolute peak. Miles Morales faces his destiny in a kaleidoscopic finale.'),

('Star Wars: New Jedi Order', 'Movie', 2027, '2h 30m', 'PG-13', 8.8, '78K', 'https://picsum.photos/seed/starwars-njo/300/450', 'https://picsum.photos/seed/starwars-njo-bg/1200/600', 'https://www.youtube.com/embed/dQw4w9WgXcQ', ARRAY['Sci-Fi', 'Adventure', 'Action'], 'English', 'for-you', 'Rey rebuilds the Jedi 15 years after TROS. A new darkness stirs — and this time, it feels personal.');
